### PR TITLE
check indentation of changes on GitHub

### PR DESCRIPTION
**Pull request by vogler**
Stumbled upon this: https://pre-commit.ci
Not sure if we want automatic commits that fix indentation in PRs.
Also, https://pre-commit.com does not list OCaml, so we might as well just add another GitHub workflow for it.

_Originally posted by @vogler in https://github.com/goblint/analyzer/issues/236#issuecomment-887556635_

Setting up OCaml just to install `ocp-indent` to check the code seems like a lot overhead, but maybe this can be cached.

### CODE REVIEW

**Comment by vogler** [comment]
Action failed with
```console
Run git reset --soft HEAD~ && ./scripts/hooks/pre-commit
fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by sim642** [comment]
This only checks the last commit, right? So if you push multiple commits, then it won't check for misindentations introduced by earlier commits that this workflow didn't run for.

**Comment by vogler** [comment]
> This only checks the last commit, right? So if you push multiple commits, then it won't check for misindentations introduced by earlier commits that this workflow didn't run for.

Ah, yes, good point.
Confusing docs, maybe reset to `${{ github.event.push.before }}` then.
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push

**Comment by vogler** [comment]
Ok, no, that's empty: `git reset --soft  `

**Comment by vogler** [comment]
Ok, `${{ github.event.before }}` works.

Setup OCaml + ocp-indent still takes 1m21s + 30s.
So it seems the caching by `ocaml/setup-ocaml@v2` is not that good (or missing some argument).
Something to consider for #296.

**Comment by vogler** [comment]
With `ocaml/setup-ocaml@v1` and manual caching the run-time decreased from ~2m to 31-35s.

**Comment by vogler** [comment]
Ok, with `apt install ocp-indent` instead of via `opam install ocp-indent` it's only 12s instead of 31s.
(ubuntu-latest is 20.04 LTS which has ocp-indent 1.7.0 instead of 1.8.1 from opam.)

At least this detour was helpful for some opam cache experiments for #296.

**Comment by michael-schwarz** [comment]
In the run https://github.com/goblint/analyzer/runs/3199968802, we have the error message

```
ocp-indent file: src/analyses/arinc.ml, lines: 122
ocp-indent: internal error, uncaught exception:
            Failure("Config file not found - neither /etc/ocamlfind.conf nor the directory /etc/ocamlfind.conf.d")
```

**Comment by vogler** [comment]
So the apt package is broken? What does it need `ocamlfind` for? Strange.
I'll just revert to `opam` and merge.

**Comment by sim642** [comment]
It's still somehow broken, cannot find `ocp-indent`: https://github.com/goblint/analyzer/runs/3201066169?check_suite_focus=true#step:6:8.

**Comment by vogler** [comment]
I added a `eval $(opam env)` before in 0f86542f188a6cc67e405c6ef977336baa33b4e8 - hope that helps. I thought ocaml-setup should take care of modifying `.profile`/`.bashrc`...

I can't resurrect this PR anymore? I committed it on its branch, but it's not showing those commits anymore after the merge...

**Comment by michael-schwarz** [comment]
https://github.com/goblint/analyzer/pull/310/checks?check_run_id=3212969178 fails with

```
Run git reset --soft 0000000000000000000000000000000000000000 && eval $(opam env) && ./scripts/hooks/pre-commit
  git reset --soft 0000000000000000000000000000000000000000 && eval $(opam env) && ./scripts/hooks/pre-commit
  shell: /usr/bin/bash -e {0}
  env:
    OPAMJOBS: 4
    OPAMYES: 1
fatal: Could not parse object '0000000000000000000000000000000000000000'.
Error: Process completed with exit code 128.
```

**Comment by vogler** [comment]
Strange that it's all 0.
`${{ github.event.before }}`: 'The SHA of the most recent commit on `ref` before the push.'([doc](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push)).
Looks like you pushed 2 commits on Aug 1, and there's a commit before on Jun 16, correct? So it should evaluate to this commit instead of all 0.
I could change it to fallback to `HEAD~` or prob. better `HEAD^` if it's all 0, but it'd be better to know what's the reason for it first.

**Comment by michael-schwarz** [comment]
> branch rename

Yes, I renamed the branch, but that was entirely local before it was published to GitHub. I'm not sure if this is visible to GitHub even, one would think the name of the local branch should not matter...
But maybe this is the cause

**Comment by sim642** [comment]
If the branch was new on GitHub, then there was no most recent commit on it (the `ref`) before the push. Technically there were the commits on master that it merges, but maybe the actions events are directly branch-based. Or maybe they just don't follow merges because it would make the value ambiguous.

This is probably more work but there's also this:

| Key | Type | Description |
| -- | -- | -- |
| `commits[][distinct]` | `boolean` | Whether this commit is distinct from any that have been pushed before. |

**Comment by vogler** [comment]
Just confirmed on https://github.com/goblint/analyzer/runs/3230967934 that the first push on a new branch has all 0.

**Comment by vogler** [comment]
https://github.com/goblint/analyzer/commit/0ce4a7dadf2fd2c644ec1bab3e8321d4498f2fcc#r55854725

https://github.com/goblint/analyzer/blob/7879abe801d3bf42067fac9a6470bd526b8ae80d/.github/workflows/indentation.yml#L46

Did you try `git reset --soft HEAD^` if it's all 0?

**Comment by sim642** [comment]
> This means the first push on a new branch won't be checked but only the following changes?

I suppose so. I just wanted those zero commit failures to go away because they made the indentation workflow too easy to ignore for false alarms.

> Did you try `git reset --soft HEAD^` if it's all 0?

That's not fully accurate either because you might push multiple commits to a new branch, but this would only consider the last of those.

**Pull request merged**
