### PR TITLE
Add emoji and Wettlaufweltmeister to ReadTheDocs

### PR DESCRIPTION
**Pull request by sim642**
ReadTheDocs preview for this PR: https://goblint--1002.org.readthedocs.build/en/1002/.

Feel free to suggest better emoji ideas.

### CODE REVIEW

**Comment by vesalvojdani** [comment]
The emojis are excellent. The huge _Wettlaufweltmeister_ is maybe a bit shocking...

**Comment by jerhard** [comment]
I particularly like the Kobold emoji 👺 for the user guide ;)

**Comment by michael-schwarz** [comment]
>  The huge Wettlaufweltmeister is maybe a bit shocking...

Maybe we can include a screenshot of Gob(view|pie)+ above him? That would make him a little less in-your-face but still very prominent.

**Comment by sim642** [comment]
> Maybe we can include a screenshot of Gob(view|pie)+ above him? That would make him a little less in-your-face but still very prominent.

@vesalvojdani added some surrounding text, which makes the image less shocking. Which reminds me that we should probably have some kind of "Goblint in the wild" page with achievements and external users in the docs, but that's out of scope for this PR.

**Review by michael-schwarz — APPROVED** [review]

**Pull request merged**
