### PR TITLE
Improving parameter of math function abs in condition

### PR DESCRIPTION
**Pull request by stilscher**
PR for issue #1244

### CODE REVIEW

**Comment by sim642** [comment]
I don't think this draft should've been merged. #1254 contained the immediate solution but making it less ad-hoc in `BaseInvariant` is still a separate matter to look at.

**Comment by michael-schwarz** [comment]
Ah, sorry, I merged the wrong thing.

**Comment by sim642** [comment]
Or maybe it automatically merged this because it was included in #1254. Because both got merged.

**Comment by michael-schwarz** [comment]
Ah, yes, that is what happened. I'll open it again

**Pull request merged**
