### PR TITLE
Move all tests to `dune runtest`

### LINKED ISSUE #1359: Define a `make` target for running relational tests
Currently, one has to run a ~5 sets separately after making changes to something related to apron. This is inconvenient.

### PR DESCRIPTION
**Pull request by sim642**
Closes #1359.

### TODO
- [x] Add fine-grained dune aliases for subsets of tests.

### CODE REVIEW

**Comment by michael-schwarz** [comment]
Nice! I think for this to close #1359 an easy to use way to run the tests (akin to `make test`) and updates to the documentation would be good have

**Comment by sim642** [comment]
> Also, we should investigate why the MacOS CI now fails.

I occasionally saw one-off failures locally on Ubuntu as well. I suspect this is due to higher CPU load: if there are enough cores, then dune runs for example all the Apron groups in parallel, which were sequential CI job steps before.

**Comment by michael-schwarz** [comment]
> > Also, we should investigate why the MacOS CI now fails.
> 
> I occasionally saw one-off failures locally on Ubuntu as well. I suspect this is due to higher CPU load: if there are enough cores, then dune runs for example all the Apron groups in parallel, which were sequential CI job steps before.

Should we in this case not pass `-j 1` to dune to ensure that things are sequential in the CI? I think reproducible and reliable CI runs are  well worth some slowdown.

**Comment by sim642** [comment]
It's not just the CI though. It can also happen locally where we want things to be parallel. I'll see if dune locks help with this.

**Review by michael-schwarz — APPROVED** [review]

**Comment by DrMichaelPetter** [comment]
Can I haz better error output? ;-)

`make: *** [Makefile:4: test] Error 1`

Error 1 is a little bit too much guesswork for a newb like me. On the other hand, I get lots of information that concern tests that I did not touch. Lets take my current project in focus. I get the line

`No errors :)0 lin2vareq/cast-non-intn-steroids`

Why is exactly this particular test out of all the 70 mentioned here explicitely if there are no errors? 
  

```
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Ran: 2986 tests in: 12.89 seconds.
OK
Missing linux-headers, will download now!
Excellent: ignored check on ../11-restart/13-changed_start_state2.c:10 is now passing!
Excellent: ignored check on ../11-restart/13-changed_start_state2.c:11 is now passing!
No errors :)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5746k    0 5746k    0     0  5204k      0 --:--:--  0:00:01 --:--:-- 7685k
No errors :)4 manual-restart/restarting_and_abortingotation-dyn
Excellent: ignored check on tests/regression/04-mutex/58-pthread-lock-return.c:73 is now passing!
Excellent: ignored check on tests/regression/04-mutex/58-pthread-lock-return.c:82 is now passing!
Excellent: ignored check on tests/regression/04-mutex/58-pthread-lock-return.c:87 is now passing!
Excellent: ignored check on tests/regression/57-floats/15-more-library.c:42 is now passing!
Excellent: ignored check on tests/regression/57-floats/15-more-library.c:56 is now passing!
Excellent: ignored check on tests/regression/57-floats/17-other.c:18 is now passing!
No errors :)
No errors :)7 octagon/addressctagon_keep_last_prec
Excellent: ignored check on tests/regression/36-apron/21-traces-cluster-based.c:48 is now passing!
Excellent: ignored check on tests/regression/36-apron/21-traces-cluster-based.c:66 is now passing!
Excellent: ignored check on tests/regression/36-apron/21-traces-cluster-based.c:69 is now passing!
Excellent: ignored check on tests/regression/36-apron/22-traces-write-centered-vs-meet-mutex.c:25 is now passing!
Excellent: ignored check on tests/regression/36-apron/34-large-bigint.c:18 is now passing!
Excellent: ignored check on tests/regression/36-apron/38-branch-global.c:13 is now passing!
Excellent: ignored check on tests/regression/36-apron/42-threadenter-arg.c:6 is now passing!
No errors :)
File "tests/regression/46-apron2/dune", line 1, characters 0-319:
 1 | (rule
 2 |  (aliases runtest runaprontest)
 3 |  (enabled_if %{lib-available:apron})
 4 |  (deps
 5 |    (package goblint)
 6 |    ../../../goblint ; update_suite calls local goblint
 7 |    (:update_suite ../../../scripts/update_suite.rb)
 8 |    (glob_files ??-*.c))
 9 |  (locks /update_suite)
10 |  (action (chdir ../../.. (run %{update_suite} group apron2))))
Testing 46/79 apron2/fixpointtin Status: 3 (verify)zec
  - [Error][Unsound] Fixpoint not reached

Excellent: ignored check on tests/regression/46-apron2/75-mutex_with_ghosts.c:56 is now passing!
46/79 failed!

1 test(s) failed: ["46/79 fixpoint"]
No errors :)9 apron-mukherjee/mukherjee_fig_3_11ngesth_uninit
No errors :)0 affeq/svcomp-signextension         
No errors :)0 lin2vareq/cast-non-intn-steroids   
Excellent: ignored check on tests/regression/78-termination/25-leave-loop-goto-terminating.c for term is now passing!
Excellent: ignored check on tests/regression/78-termination/28-do-while-continue-terminating.c for term is now passing!
No errors :)
make: *** [Makefile:4: test] Error 1             
```

**Pull request merged**
