### PR TITLE
Fix var_eq from keeping equalities with pointers to globals

### PR DESCRIPTION
**Pull request by sim642**
See https://github.com/goblint/analyzer/issues/141#issuecomment-732080297.

### CODE REVIEW

**Comment by sim642** [comment]
The original pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.i has following in the global invariant:
* `whoop_loff_t -> Address {&(alloc@...)}`
* `&(alloc@...) -> Blob (Int)`
I don't understand how `NULL` isn't in the address set of `whoop_loff_t` anymore, because it is zero-initialized to that.

In both of the minimized versions I've committed here, the `NULL` remains there and the malloc also adds unknown pointer:
* `whoop_loff_t -> Address {NULL, ?}`
* `&(alloc@...) -> Blob (Bot)`
The PR handles both cases but it'd be great to actually also test that but I'm very confused how the original behavior is even possible.

**Comment by michael-schwarz** [comment]
> I don't understand how NULL isn't in the address set of whoop_loff_t anymore, because it is zero-initialized to that.

We don't have early globals on in `sv-comp`. And it only goes to multithreading after `whoop_loff_t` is set if I see it correctly? So this should be the expected behavior, no?

**Comment by sim642** [comment]
But the 29/20 I committed should then behave the same way, by starting out single threaded as well, but for whatever reason it doesn't.

**Comment by michael-schwarz** [comment]
> But the 29/20 I committed should then behave the same way, by starting out single threaded as well, but for whatever reason it doesn't.

True, that is indeed strange! I'll take a  look maybe, I can see what's going on.

**Comment by michael-schwarz** [comment]
If you add `#include <stdlib.h>` to your example program, it behaves just like the big example.

**Comment by michael-schwarz** [comment]
I think we can merge this now

**Comment by sim642** [comment]
> If you add `#include <stdlib.h>` to your example program, it behaves just like the big example.

Of course, thanks for noticing that! I now remember fixing a similar thing in a previous regression test.

It's so annoying though that due to `malloc` being so specialized we don't have any warnings about it even lacking a _declaration_ and that `int` is implicitly assumed to be the return type, which really screws with base analysis.

**Pull request merged**
