### PR TITLE
Enable constant loop unrolling for small files

### PR DESCRIPTION
**Pull request by leunam99**
This adds two small features to the autotuner:
If there are less than 5 loops, they all get unrolled at least 10 times
If the file is small, the congruence domain is enabled.

### CODE REVIEW

**Comment by michael-schwarz** [comment]
I moved the congruence changes over to #911 so we have two separate PRs.

**Comment by michael-schwarz** [comment]
With less than 5 loops, for sv-comp this does not trigger anywhere.

**Comment by michael-schwarz** [comment]
To get the results for the tasks we care about to change, we need to apply this if there are less than 17 loops. Will still benchmark that, but it is dubious if this will be positive overall.

**Comment by michael-schwarz** [comment]
We will not have time to benchmark this in time for the deadline, so let's move it to 2024.

**Comment by michael-schwarz** [comment]
I have now moved this to a separate autotuner `forceLoopUnrollForFewLoops` that is disabled by default. I propose to merge this now in the interest of reducing the number of stale PRs. We may then investigate the benefits of this option when it is time to prepare the configuration for this year's SV-Comp.

**Review by sim642 — APPROVED** [review]

**Pull request merged**
