### PR TITLE
Remove outdated and broken ocamlbuild

### PR DESCRIPTION
**Pull request by sim642**
AFAIK nobody is using these ocamlbuild rules for anything anymore. I tried to and they're utterly broken as well because our dune setup has evolved considerably to all sorts of advanced mechanisms: alternative dependencies for Apron and Z3; virtual libraries for dune-site (and Gobview). It's probably not worth the effort trying to make the inferior ocamlbuild work, so we can just drop the unnecessary dependency.

On a related note, we still have the `travis-ci.sh` script, which we don't use for CI anymore, but `Vagrantfile` does. It contains the following line:
https://github.com/goblint/analyzer/blob/0da0464dfd65c3d84566a71b55f9e5f19b218843/scripts/travis-ci.sh#L21
Now that the ocamlfind dependency is also dropped, do we not need `m4` anymore? I don't know what it would be needed for, but currently we still claim to require it in our README etc.

### CODE REVIEW

**Comment by michael-schwarz** [comment]
This also removes our way of building unittests and the `mainarinc` executable. Is this intended?
If yes, we should discuss whether those things should be removed.

If no, we should add the possibility to build those things again.

**Comment by sim642** [comment]
I tried to build the unit tests recently and that doesn't work right now anyway. They haven't been executed for so long that they just assume nonexistant modules and interfaces. Maybe we shouldn't delete them entirely yet though, because for #403 I was thinking of maybe writing some tests eventually. Given that they don't work with ocamlbuild right now anyway, this doesn't make their building any worse.

I have no idea about `mainarinc` though. Probably hasn't been built in forever either.

**Comment by sim642** [comment]
Actually, I just remembered: `mainarinc` is listed under `modules` here:
https://github.com/goblint/analyzer/blob/fd4aecfa33db6f74de6ec0b510cf03aa570cc053/src/dune#L49-L53

But I have no idea what that's supposed to mean because it's not given an executable name and the existing ones don't even match up with the listed modules.

**Comment by michael-schwarz** [comment]
`mainarinc` still compiles though. It seems to take a marshalled ARINC result and then print some Promela model and dot graph.
Maybe @vogler knows the details here, and whether this executable is worth keeping?

I think this model extraction for ARINC/pthreads is something that we should keep also in the "slim" Goblint.

**Comment by sim642** [comment]
I just tried as well that both `mainarinc` and `mainspec` compile with dune, so I added them. Interesting how `mainspec` was already listed under `modules`, but there wasn't anything in make for that.

Also, apparently `names` and `modules` don't need to zip up, but `names` themselves are names of modules and `modules` is just there because we reuse the directory also for the library.

**Review by michael-schwarz — APPROVED** [review]

**Comment by vogler** [comment]
> `mainarinc` still compiles though. It seems to take a marshalled ARINC result and then print some Promela model and dot graph. Maybe @vogler knows the details here, and whether this executable is worth keeping?
> 
> I think this model extraction for ARINC/pthreads is something that we should keep also in the "slim" Goblint.

Yes, it's the Promela codegen part which also has some options for which you don't want to re-run the analysis.
Those other main* could be integrated into `maingoblint.ml`, but IMO that's too messy (and pulls in a lot of deps for their build).

**Pull request merged**
