### PR TITLE
Add query answer to EvalInt and EvalInterval in the poly analysis

### PR DESCRIPTION
**Pull request by isabelmax**
- added the function of_interval to the signature of the int domains (commit bc7268b)
- refactored the apronDomain such that the functions transforming cil expressions to apron expressions have names that can be distinguished easier (commit 0fa9ee7)
- added functions to answer EvalInt and EvalInterval (commit b8b9475)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/goblint/analyzer/pull/43%23issuecomment-171952782%22%2C%20%22https%3A//github.com/goblint/analyzer/pull/43%23issuecomment-172764747%22%2C%20%22https%3A//github.com/goblint/analyzer/pull/43%23issuecomment-172772091%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/goblint/analyzer/pull/43%23issuecomment-171952782%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Could%20you%20change%20%60val%20of_interval%3A%20int64%20-%3E%20int64%20-%3E%20t%60%20to%20%60val%20of_interval%3A%20int64%20%2A%20int64%20-%3E%20t%60%3F%20Then%20there%27s%20no%20need%20for%20%60poly2_in/createTwoParams%60.%22%2C%20%22created_at%22%3A%20%222016-01-15T12%3A54%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/493741%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vogler%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20we%20merge%20it%3F%22%2C%20%22created_at%22%3A%20%222016-01-19T07%3A36%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8916408%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/isabelmax%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sorry%2C%20didn%27t%20see%20the%20commit.%22%2C%20%22created_at%22%3A%20%222016-01-19T08%3A17%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/493741%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vogler%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/goblint/analyzer/pull/43#issuecomment-171952782'>General Comment</a></b>
- <a href='https://github.com/vogler'></a> Could you change `val of_interval: int64 -> int64 -> t` to `val of_interval: int64 * int64 -> t`? Then there's no need for `poly2_in/createTwoParams`.
- <a href='https://github.com/isabelmax'></a> Can we merge it?
- <a href='https://github.com/vogler'></a> Sorry, didn't see the commit.

<a href='https://www.codereviewhub.com/goblint/analyzer/pull/43?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/goblint/analyzer/pull/43?approve=1'></a>&nbsp;<a href='https://github.com/goblint/analyzer/pull/43'></a>
<a href='#crh-end'></a>

[Review on Reviewable](https://reviewable.io/reviews/goblint/analyzer/43)

***
***
***

### CODE REVIEW

**Comment by vogler** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/goblint/analyzer/pull/43'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by vogler** [comment]
Could you change `val of_interval: int64 -> int64 -> t` to `val of_interval: int64 * int64 -> t`? Then there's no need for `poly2_in/createTwoParams`.

**Comment by isabelmax** [comment]
Can we merge it?

**Comment by vogler** [comment]
Sorry, didn't see the commit.

**Pull request merged**
