### PR TITLE
Fix `cast` for `IBool`

### LINKED ISSUE #1064: Double logical negation is more precise than cast to `bool`
In the following example, the cast of a non-`NULL` pointer to `bool` is imprecise while double logical negation (or inequality check equivalent to cast to `bool`) is precise:
```c
#include <stdbool.h>

int main() {
  int a;
  int *p = &a;

  bool x = p; // Unknown int([0,1])
  bool y = !!p; // 1
  bool z = p != 0; // 1
  return 0;
}
```

> ### 6.3.1.2 Boolean type
> 1. When any scalar value is converted to `_Bool`, the result is 0 if the value compares equal to 0; otherwise, the result is 1.

where 

> Arithmetic types and pointer types are collectively called scalar types.

I think we currently just find that the target type of the cast is smaller than the source type, so it's a downcast and thus precision is lost.

### LINKED ISSUE #1110: Casts to `_Bool` are unsound
Consider, e.g.,

~~~C
#include <stdbool.h>
#include <assert.h>

int main() {
  int b = 10;
  bool bb = b;
  __goblint_check(bb);
  return 0;
}
~~~

Goblint currently claims the `__goblint_check` will always fail, however in C it should always succeed.

### PR DESCRIPTION
**Pull request by michael-schwarz**
Closes #1064. (imprecision)
Closes #1110 (unsoundness)

### CODE REVIEW

**Comment by sim642** [comment]
Some int domain property tests are failing here:
```
 ==============================================================================
Error: :7:domaintest:1556:integerset -> congruences (_Bool): valid shift_left.

File "/home/runner/work/analyzer/analyzer/_build/default/unittest/oUnit--fv-az592-596#02.log", line 4957, characters 1-1:
Error: :7:domaintest:1556:integerset -> congruences (_Bool): valid shift_left (in the log).

File "src/core/QCheck2.ml", line 1843, characters 1-1:
Error: :7:domaintest:1556:integerset -> congruences (_Bool): valid shift_left (in the code).


test `integerset -> congruences (_Bool): valid shift_left`
failed on ≥ 1 cases: ([1L], [1L])
                       

------------------------------------------------------------------------------
==============================================================================
Error: :7:domaintest:1552:integerset -> congruences (_Bool): valid bitnot.

File "/home/runner/work/analyzer/analyzer/_build/default/unittest/oUnit--fv-az592-596#01.log", line 4784, characters 1-1:
Error: :7:domaintest:1552:integerset -> congruences (_Bool): valid bitnot (in the log).

File "src/core/QCheck2.ml", line 1843, characters 1-1:
Error: :7:domaintest:1552:integerset -> congruences (_Bool): valid bitnot (in the code).


test `integerset -> congruences (_Bool): valid bitnot` failed on ≥ 1 cases:
[1L]


------------------------------------------------------------------------------
==============================================================================
Error: :7:domaintest:1541:integerset -> congruences (_Bool): valid add.

File "/home/runner/work/analyzer/analyzer/_build/default/unittest/oUnit--fv-az592-596#02.log", line 4904, characters 1-1:
Error: :7:domaintest:1541:integerset -> congruences (_Bool): valid add (in the log).

File "src/core/QCheck2.ml", line 1843, characters 1-1:
Error: :7:domaintest:1541:integerset -> congruences (_Bool): valid add (in the code).


test `integerset -> congruences (_Bool): valid add` failed on ≥ 1 cases:
([1L], [1L])
```

**Comment by michael-schwarz** [comment]
Yes, I'll have a look. I am wondering a bit about whether it's the implementation or the tests that are at fault here. `_Bool` behaves strangely in that `1+1=1` (via promotion to ints).

**Comment by michael-schwarz** [comment]
```
==============================================================================
Error: :7:domaintest:1556:integerset -> congruences (_Bool): valid shift_left.

File "/home/michael/Documents/goblint-cil/analyzer/_build/default/unittest/oUnit--michael-ThinkPad-X1-Carbon-6th#03.log", line 2449, characters 1-1:
Error: :7:domaintest:1556:integerset -> congruences (_Bool): valid shift_left (in the log).

File "src/core/QCheck2.ml", line 1843, characters 1-1:
Error: :7:domaintest:1556:integerset -> congruences (_Bool): valid shift_left (in the code).


test `integerset -> congruences (_Bool): valid shift_left`
failed on ≥ 1 cases: ([1L], [1L])

Invalid: concrete: {2}  abstract: 0                       

------------------------------------------------------------------------------
==============================================================================
Error: :7:domaintest:1552:integerset -> congruences (_Bool): valid bitnot.

File "/home/michael/Documents/goblint-cil/analyzer/_build/default/unittest/oUnit--michael-ThinkPad-X1-Carbon-6th#02.log", line 2468, characters 1-1:
Error: :7:domaintest:1552:integerset -> congruences (_Bool): valid bitnot (in the log).

File "src/core/QCheck2.ml", line 1843, characters 1-1:
Error: :7:domaintest:1552:integerset -> congruences (_Bool): valid bitnot (in the code).


test `integerset -> congruences (_Bool): valid bitnot` failed on ≥ 1 cases:
[1L]


Invalid: concrete: {2}  abstract: 0

------------------------------------------------------------------------------
==============================================================================
Error: :7:domaintest:1541:integerset -> congruences (_Bool): valid add.

File "/home/michael/Documents/goblint-cil/analyzer/_build/default/unittest/oUnit--michael-ThinkPad-X1-Carbon-6th#03.log", line 2414, characters 1-1:
Error: :7:domaintest:1541:integerset -> congruences (_Bool): valid add (in the log).

File "src/core/QCheck2.ml", line 1843, characters 1-1:
Error: :7:domaintest:1541:integerset -> congruences (_Bool): valid add (in the code).


test `integerset -> congruences (_Bool): valid add` failed on ≥ 1 cases:
([1L], [1L])

Invalid: concrete: {-2}  abstract: 0
```

**Comment by michael-schwarz** [comment]
I have removed the quickcheck tests for bools now. The notion of what arithmetic that doesn't go through the usual promotions is supposed to do seems unclear for `_Bool` to me. The standard does not provide any help either, as none of these operations are defined without promotion to `int`.

I think this is not perfect, but for sure better than what we currently have, and I would vote to merge it.

I unfortunately cannot dedicate more time to this at the moment.

**Review by sim642 — APPROVED** [review]

**Comment by sim642** [comment]
Indeed, congruences modulo 2 aren't compatible with `_Bool` semantics so it's unclear how that should work.

**Pull request merged**
