### PR TITLE
Add "ERROR (both branches dead)" verdict for SV-COMP

### LINKED ISSUE #1576: `ERROR` verdict for both branches dead in SV-COMP
Apparently there are SV-COMP tasks where we output the "both branches dead" unsoundness warning, but still happily give a `true` SV-COMP result. We've been lucky that this hasn't caused unsound verdicts.
In these cases the verdict should instead be something like `ERROR (both branches dead)`.

We do this for fixpoint errors with `ERROR (fixpoint)`.

### PR DESCRIPTION
**Pull request by sim642**
Closes #1576.

### CODE REVIEW

**Comment by michael-schwarz** [comment]
Before merging this we should verify that it is not just because the condition transfer functions are quite strong that we end up with this warning because the predecessor is in fact unreachable.

**Comment by sim642** [comment]
We should have this behavior either way independently of any particular task if we want to be serious about soundness.
If the both branches dead warning is triggered too generously, that's a separate precision problem for that.

**Review by michael-schwarz — COMMENTED** [review]
LGTM! We should keep a keen lookout for the instances of this.

I'm still wondering if if we can devise some way to not raise this when it's simply to imprecision of domains (Maybe don't raise it for Polyhedra at all now?)

**Comment by sim642** [comment]
I tried forcing Apron to somehow reduce integer constraints in #1585 to avoid the spurious cautiousness but none of it is particularly nice.
We should see from (our own) pre-runs how often this actually comes up on sv-benchmarks and then decide what to do about these.

**Pull request merged**
