### PR TITLE
Change `Machdep` based on SV-COMP architecture

### LINKED ISSUE #54: make sizes of primitive types configurable with current machine as default
Cil's defaults are generated from `src/machdep-ml.c.in` and then stored in `_build/machdep.ml`.

- [ ] make `Machdep.theMachine` configurable in goblint
- [ ] provide default configurations {intel, arm} {32bit, 64bit} {linux, macOS}

### LINKED ISSUE #1385: Unsoundness on SV-COMP for No-Overflow & Memory Properties
Noticed during benchmarking of #1354 but already present on master at 8c485c924

## No-Overflow

- [x] `./goblint --conf conf/svcomp24.json --sets ana.specification ~/Documents/sv-comp/sv-benchmarks/c/properties/no-overflow.prp --sets exp.architecture 32bit ~/Documents/sv-comp/sv-benchmarks/c/ldv-regression/test_overflow.i` (#54) Task fixed upstream: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1552.

## Mem-Safety

- [x] `./goblint --conf conf/svcomp24.json --sets ana.specification ~/Documents/sv-comp/sv-benchmarks/c/properties/valid-memsafety.prp --sets exp.architecture 32bit ~/Documents/sv-comp/sv-benchmarks/c/list-ext3-properties/sll_shallow_copy-2.i` (#1388)

## Mem-Cleanup

- [x] `./goblint --conf conf/svcomp24.json --sets ana.specification ~/Documents/sv-comp/sv-benchmarks/c/properties/valid-memcleanup.prp --sets exp.architecture 32bit ~/Documents/sv-comp/sv-benchmarks/c/list-properties/list_search-1.i` (#1388)
- [x] `./goblint --conf conf/svcomp24.json --sets ana.specification ~/Documents/sv-comp/sv-benchmarks/c/properties/valid-memcleanup.prp --sets exp.architecture 32bit ~/Documents/sv-comp/sv-benchmarks/c/list-properties/list_search-2.i` (#1388)

### PR DESCRIPTION
**Pull request by sim642**
Closes #54, at least for SV-COMP usage.

### TODO
- [x] Merge https://github.com/goblint/cil/pull/173.
- [x] Why doesn't fix #1385/#1501? It has overflow in cast.
- [x] Add tests.
- [x] Run on sv-benchmarks.
- [x] Fix MacOS CI.

### CODE REVIEW

**Comment by michael-schwarz** [comment]
I think we should investigate the 55 new `EXCEPTION (IntDomain.IncompatibleIKinds` exceptions before merging, while we still have an idea of what could be the case.

Also, when this is addressed, I think it makes sense to do a full ressource run the state before this and after it on `server01` here before merging. I can start it if you ping me.

**Comment by michael-schwarz** [comment]
The runs for the context gas values are now finished, I just started the comparison run on the current master (approx 24h), and will then start the run with this after.

**Comment by michael-schwarz** [comment]
The comparison run I started yesterday has finished this morning, I Just started https://github.com/goblint/analyzer/tree/staging_machdep-arch now.

**Review by michael-schwarz — APPROVED** [review]
Good to go from my view as soon as the OS X issue is fixed.

**Comment by sim642** [comment]
For now I disabled the test on MacOS. But I also added error messages about the missing machine definition. At least it's still possible to do SV-COMP runs on MacOS for ILP32 tasks but there will be a clear message about the possible unsoundness. The alternative would be to just crash when the machdep is missing, but that might be too harsh and inconvenient (because `-m64` probably also doesn't work).

In the future we might want to provide pre-generated machdeps in CIL (at least for type sizes if not all machdep components). That should be enough for SV-COMP where preprocessing isn't needed.

**Pull request merged**
